### ISSUE TITLE
May I have the change to get the source code?

### ISSUE THREAD

**Issue by Lisprez** [mustafaquraish/cup#4]
Thanks for your great work.
I would like to get the source code which produce the bootstrap assembly code.

Maybe you write the bootstrap code in C, Rust .. 

Thanks.

**Comment by mustafaquraish** [comment]
That depends on what you mean by "the bootstrap assembly code". If you're referring to the current version of the assembly code, the source code that generates that is already in the repo (in the `compiler/` folder). If you're referring to the _first_ version of the bootstrap code, the C code used to generate that can be found in the history here: https://github.com/mustafaquraish/cup/commit/758d87b8757a5e228e887af5d3dbcbdfa5a48405. 

Do note that the old C compiler lacks many of the features that the current version of the compiler has, so that version of the code will not do much to help you. Instead, you should follow the instructions in the README to generate the bootstrap compiler from the provided assembly, and the resulting compiler can then compile the newest version of the source in `compiler/` to generate assembly files.

**Comment by Lisprez** [comment]
Thank you very much, you have answered my question
