### ISSUE TITLE
Cannot build on macOS BigSur version11.6

### ISSUE THREAD

**Issue by yu1hpa** [mustafaquraish/cup#6]
Build Issue
**Environment**
macOS BigSur version 11.6

**Description**
I was trying to follow the installation guide.
I can't seem to build it on macOS BigSur.

**What I did**
First of all, I googled this error.
```
$ ./meta/bootstrap.sh
[+] Compiling the bootstrap compiler...
ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
```

https://stackoverflow.com/a/65570573

In accordance with this, fixed.
(meta/bootstrap.sh)
```
   Darwin)
        cp bootstrap/macos.yasm bootstrap/cupcc.yasm
        yasm -f macho64 -o bootstrap/cupcc.o bootstrap/cupcc.yasm
        ld -o bootstrap/cupcc bootstrap/cupcc.o -macosx_version_min 11.6 -L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -lSystem
        ;;
```

Then, I cannnot fix the next error.
```
$ ./meta/bootstrap.sh
[+] Compiling the bootstrap compiler...
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in func_die from bootstrap/cupcc.o. To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
[+] Creating build/cupcc with bootstrap compiler...
[+] /usr/local/bin/yasm -fmacho64 -o build/cupcc.o build/cupcc.yasm
[+] /usr/bin/ld -o build/cupcc build/cupcc.o -lSystem
ld: library not found for -lSystem
std/common.cup:350:14: Child exited with non-zero status: (1)
```

**Comment by mustafaquraish** [comment]
The issue here is that the first round of compilation is happening successfully with the flags you passed in, but internally, the bootstrap compiler also calls `ld` to link the new executable, but the flags are not being passed in there unfortunately. For now, you can just link `build/cupcc.o` manually, and edit `compiler/main.cup` to include the new flags to the `ld` call, and then run compile a newer version of the compiler.

Perhaps the better fix here might be to just use `clang` for linking as opposed to `ld`, and it will pass all the correct arguments to the linker call. Changing the linking step to `clang XXX.o -o XXX` (in both the `meta/bootstrap.sh` file and `compiler/main.cup`) seems to do the trick for me, but I'm not sure if that might be different on your version.

Thanks for pointing this out, I didn't know there would be weird stuff with different macOS versions, I'll look into this further, and see if I can push a change to the repo within the next few days that just lets it work out of the box. I think Github Actions has macOS 11, so I might be able to test there.

 It's a bit of an annoyance getting the initial workflow up, but after that it's usually fine. You can reach out on Discord if you're still interested in getting it working and want some help: mustafaq#8791

**Comment by mustafaquraish** [comment]
For the error you have right now at least, since the `build/cupcc.o` has been generated, you can just link that manually to be able to get an executable (so that you can re-bootstrap your local compiler after changing the command in `compiler/main.cup`). It's a bit of an annoyance getting the initial workflow up, but after that it's usually fine. You can reach out on Discord if you're still interested in getting it working and want some help: mustafaq#8791

**Comment by mustafaquraish** [comment]
Actually, it was a simple enough fix. I've updated the code to use `clang` for linking on macOS, and I've also added a test runner for macOS 11 to make sure we don't regress. If you just checkout the newest master, it should work fine now on your machine. Thanks again for taking the time to point out the bug!
